"""Initial registry schema

Revision ID: f911815a8772
Revises:
Create Date: 2026-08-07 20:57:02.974293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'f911815a8772'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tenant',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table(
        'environment',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('sandbox', 'staging', 'production', name='environment_kind'),
            nullable=False,
        ),
        sa.Column('compute_boundary_ref', sa.String(length=255), nullable=False),
        sa.Column('network_boundary_ref', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'name', name='uq_environment_tenant_name'),
    )
    op.create_index(
        op.f('ix_environment_tenant_id'), 'environment', ['tenant_id'], unique=False
    )
    op.create_table(
        'principal',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('user', 'agent', 'service_account', name='principal_kind'),
            nullable=False,
        ),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'tenant_id', 'external_id', name='uq_principal_tenant_external_id'
        ),
    )
    op.create_index(
        op.f('ix_principal_tenant_id'), 'principal', ['tenant_id'], unique=False
    )
    op.create_table(
        'agent',
        sa.Column(
            'layer',
            sa.Enum('infra_ops', 'business_tech', 'business_ops', name='layer'),
            nullable=False,
        ),
        sa.Column(
            'llm_config',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column(
            'memory_scope',
            sa.Enum('session', 'user', 'org', 'none', name='memory_scope'),
            nullable=False,
        ),
        sa.Column(
            'permission_boundary',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            sa.Enum(
                'experimental', 'beta', 'stable', 'deprecated', name='maturity_level'
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            sa.Enum(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_id', 'version', name='uq_agent_entity_version'),
    )
    op.create_index(
        'ix_agent_current_version',
        'agent',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(op.f('ix_agent_entity_id'), 'agent', ['entity_id'], unique=False)
    op.create_index(op.f('ix_agent_slug'), 'agent', ['slug'], unique=False)
    op.create_index(op.f('ix_agent_tenant_id'), 'agent', ['tenant_id'], unique=False)
    op.create_table(
        'capability',
        sa.Column(
            'target_metrics',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            sa.Enum(
                'experimental', 'beta', 'stable', 'deprecated', name='maturity_level'
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            sa.Enum(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'entity_id', 'version', name='uq_capability_entity_version'
        ),
    )
    op.create_index(
        'ix_capability_current_version',
        'capability',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(
        op.f('ix_capability_entity_id'), 'capability', ['entity_id'], unique=False
    )
    op.create_index(op.f('ix_capability_slug'), 'capability', ['slug'], unique=False)
    op.create_index(
        op.f('ix_capability_tenant_id'), 'capability', ['tenant_id'], unique=False
    )
    op.create_table(
        'dataproduct',
        sa.Column(
            'contract',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            sa.Enum(
                'experimental', 'beta', 'stable', 'deprecated', name='maturity_level'
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            sa.Enum(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'entity_id', 'version', name='uq_dataproduct_entity_version'
        ),
    )
    op.create_index(
        'ix_dataproduct_current_version',
        'dataproduct',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(
        op.f('ix_dataproduct_entity_id'), 'dataproduct', ['entity_id'], unique=False
    )
    op.create_index(op.f('ix_dataproduct_slug'), 'dataproduct', ['slug'], unique=False)
    op.create_index(
        op.f('ix_dataproduct_tenant_id'), 'dataproduct', ['tenant_id'], unique=False
    )
    op.create_table(
        'datasource',
        sa.Column(
            'kind',
            sa.Enum(
                'database', 'api', 'vector_store', 'stream', name='datasource_kind'
            ),
            nullable=False,
        ),
        sa.Column('connection_binding_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            sa.Enum(
                'experimental', 'beta', 'stable', 'deprecated', name='maturity_level'
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            sa.Enum(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'entity_id', 'version', name='uq_datasource_entity_version'
        ),
    )
    op.create_index(
        'ix_datasource_current_version',
        'datasource',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(
        op.f('ix_datasource_entity_id'), 'datasource', ['entity_id'], unique=False
    )
    op.create_index(op.f('ix_datasource_slug'), 'datasource', ['slug'], unique=False)
    op.create_index(
        op.f('ix_datasource_tenant_id'), 'datasource', ['tenant_id'], unique=False
    )
    op.create_table(
        'eval_suite',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'target_entity_type',
            sa.Enum(
                'agent',
                'skill',
                'tool',
                'capability',
                'datasource',
                'dataproduct',
                name='versioned_entity_kind',
            ),
            nullable=False,
        ),
        sa.Column(
            'criteria',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'slug', name='uq_eval_suite_tenant_slug'),
    )
    op.create_index(
        op.f('ix_eval_suite_tenant_id'), 'eval_suite', ['tenant_id'], unique=False
    )
    op.create_table(
        'policy',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'effect', sa.Enum('allow', 'deny', name='policy_effect'), nullable=False
        ),
        sa.Column(
            'scope_type',
            sa.Enum(
                'entity',
                'invocation',
                'data_scope',
                'environment',
                name='policy_scope_type',
            ),
            nullable=False,
        ),
        sa.Column(
            'rule',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_policy_tenant_id'), 'policy', ['tenant_id'], unique=False)
    op.create_table(
        'role_binding',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('principal_id', sa.Uuid(), nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.Column(
            'scope_type',
            sa.Enum(
                'entity',
                'invocation',
                'data_scope',
                'environment',
                name='policy_scope_type',
            ),
            nullable=False,
        ),
        sa.Column(
            'scope_ref',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('environment_id', sa.Uuid(), nullable=True),
        sa.Column('delegated_from_principal_id', sa.Uuid(), nullable=True),
        sa.Column(
            'permission_subset',
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'
            ),
            nullable=True,
        ),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'delegated_from_principal_id IS NULL OR permission_subset IS NOT NULL',
            name='ck_role_binding_delegation_requires_subset',
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['delegated_from_principal_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['environment_id'],
            ['environment.id'],
        ),
        sa.ForeignKeyConstraint(
            ['principal_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_role_binding_principal_id'),
        'role_binding',
        ['principal_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_role_binding_tenant_id'), 'role_binding', ['tenant_id'], unique=False
    )
    op.create_table(
        'skill',
        sa.Column(
            'layer',
            sa.Enum('infra_ops', 'business_tech', 'business_ops', name='layer'),
            nullable=False,
        ),
        sa.Column(
            'kind', sa.Enum('atomic', 'composite', name='skill_kind'), nullable=False
        ),
        sa.Column('is_entry_point', sa.Boolean(), nullable=False),
        sa.Column(
            'atomic_content',
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'
            ),
            nullable=True,
        ),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            sa.Enum(
                'experimental', 'beta', 'stable', 'deprecated', name='maturity_level'
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            sa.Enum(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'atomic' AND atomic_content IS NOT NULL) OR (kind = 'composite' AND atomic_content IS NULL)",
            name='ck_skill_atomic_content_matches_kind',
        ),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_id', 'version', name='uq_skill_entity_version'),
    )
    op.create_index(
        'ix_skill_current_version',
        'skill',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(op.f('ix_skill_entity_id'), 'skill', ['entity_id'], unique=False)
    op.create_index(op.f('ix_skill_slug'), 'skill', ['slug'], unique=False)
    op.create_index(op.f('ix_skill_tenant_id'), 'skill', ['tenant_id'], unique=False)
    op.create_table(
        'tool',
        sa.Column(
            'invocation_spec',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('auth_binding_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            sa.Enum(
                'experimental', 'beta', 'stable', 'deprecated', name='maturity_level'
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            sa.Enum(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_id', 'version', name='uq_tool_entity_version'),
    )
    op.create_index(
        'ix_tool_current_version',
        'tool',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(op.f('ix_tool_entity_id'), 'tool', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tool_slug'), 'tool', ['slug'], unique=False)
    op.create_index(op.f('ix_tool_tenant_id'), 'tool', ['tenant_id'], unique=False)
    op.create_table(
        'audit_event',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column(
            'occurred_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('actor_principal_id', sa.Uuid(), nullable=False),
        sa.Column('acting_as_principal_id', sa.Uuid(), nullable=True),
        sa.Column('action', sa.String(length=255), nullable=False),
        sa.Column('entity_type', sa.String(length=64), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=True),
        sa.Column('environment_id', sa.Uuid(), nullable=True),
        sa.Column(
            'decision', sa.Enum('allow', 'deny', name='audit_decision'), nullable=False
        ),
        sa.Column('policy_id', sa.Uuid(), nullable=True),
        sa.Column(
            'details',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['acting_as_principal_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['actor_principal_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['environment_id'],
            ['environment.id'],
        ),
        sa.ForeignKeyConstraint(
            ['policy_id'],
            ['policy.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_audit_event_tenant_id'), 'audit_event', ['tenant_id'], unique=False
    )
    op.create_table(
        'capability_realization',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('capability_id', sa.Uuid(), nullable=False),
        sa.Column(
            'realizing_entity_type',
            sa.Enum('agent', 'skill', 'tool', name='realizing_entity_type'),
            nullable=False,
        ),
        sa.Column('realizing_agent_id', sa.Uuid(), nullable=True),
        sa.Column('realizing_skill_id', sa.Uuid(), nullable=True),
        sa.Column('realizing_tool_id', sa.Uuid(), nullable=True),
        sa.Column(
            'contribution_weight', sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            '((realizing_agent_id IS NOT NULL AND realizing_skill_id IS NULL AND realizing_tool_id IS NULL) OR (realizing_skill_id IS NOT NULL AND realizing_agent_id IS NULL AND realizing_tool_id IS NULL) OR (realizing_tool_id IS NOT NULL AND realizing_agent_id IS NULL AND realizing_skill_id IS NULL))',
            name='ck_capability_realization_one_realizer',
        ),
        sa.ForeignKeyConstraint(
            ['capability_id'],
            ['capability.id'],
        ),
        sa.ForeignKeyConstraint(
            ['realizing_agent_id'],
            ['agent.id'],
        ),
        sa.ForeignKeyConstraint(
            ['realizing_skill_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['realizing_tool_id'],
            ['tool.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_capability_realization_capability_id'),
        'capability_realization',
        ['capability_id'],
        unique=False,
    )
    op.create_table(
        'dataproduct_lineage',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('dataproduct_id', sa.Uuid(), nullable=False),
        sa.Column('source_datasource_id', sa.Uuid(), nullable=True),
        sa.Column('source_dataproduct_id', sa.Uuid(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            '((source_datasource_id IS NOT NULL AND source_dataproduct_id IS NULL) OR (source_dataproduct_id IS NOT NULL AND source_datasource_id IS NULL))',
            name='ck_dataproduct_lineage_one_source',
        ),
        sa.ForeignKeyConstraint(
            ['dataproduct_id'],
            ['dataproduct.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_dataproduct_id'],
            ['dataproduct.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_datasource_id'],
            ['datasource.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_dataproduct_lineage_dataproduct_id'),
        'dataproduct_lineage',
        ['dataproduct_id'],
        unique=False,
    )
    op.create_table(
        'eval_run',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('eval_suite_id', sa.Uuid(), nullable=False),
        sa.Column(
            'target_entity_type',
            sa.Enum(
                'agent',
                'skill',
                'tool',
                'capability',
                'datasource',
                'dataproduct',
                name='versioned_entity_kind',
            ),
            nullable=False,
        ),
        sa.Column('target_agent_id', sa.Uuid(), nullable=True),
        sa.Column('target_skill_id', sa.Uuid(), nullable=True),
        sa.Column('target_tool_id', sa.Uuid(), nullable=True),
        sa.Column('target_capability_id', sa.Uuid(), nullable=True),
        sa.Column('target_datasource_id', sa.Uuid(), nullable=True),
        sa.Column('target_dataproduct_id', sa.Uuid(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('pending', 'running', 'passed', 'failed', name='eval_run_status'),
            nullable=False,
        ),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'results',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('triggered_by_id', sa.Uuid(), nullable=False),
        sa.Column(
            'gates_transition_to',
            sa.Enum(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
            ),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            '((target_agent_id IS NOT NULL AND target_skill_id IS NULL AND target_tool_id IS NULL AND target_capability_id IS NULL AND target_datasource_id IS NULL AND target_dataproduct_id IS NULL) OR (target_skill_id IS NOT NULL AND target_agent_id IS NULL AND target_tool_id IS NULL AND target_capability_id IS NULL AND target_datasource_id IS NULL AND target_dataproduct_id IS NULL) OR (target_tool_id IS NOT NULL AND target_agent_id IS NULL AND target_skill_id IS NULL AND target_capability_id IS NULL AND target_datasource_id IS NULL AND target_dataproduct_id IS NULL) OR (target_capability_id IS NOT NULL AND target_agent_id IS NULL AND target_skill_id IS NULL AND target_tool_id IS NULL AND target_datasource_id IS NULL AND target_dataproduct_id IS NULL) OR (target_datasource_id IS NOT NULL AND target_agent_id IS NULL AND target_skill_id IS NULL AND target_tool_id IS NULL AND target_capability_id IS NULL AND target_dataproduct_id IS NULL) OR (target_dataproduct_id IS NOT NULL AND target_agent_id IS NULL AND target_skill_id IS NULL AND target_tool_id IS NULL AND target_capability_id IS NULL AND target_datasource_id IS NULL))',
            name='ck_eval_run_one_target',
        ),
        sa.ForeignKeyConstraint(
            ['eval_suite_id'],
            ['eval_suite.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_agent_id'],
            ['agent.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_capability_id'],
            ['capability.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_dataproduct_id'],
            ['dataproduct.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_datasource_id'],
            ['datasource.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_skill_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['target_tool_id'],
            ['tool.id'],
        ),
        sa.ForeignKeyConstraint(
            ['triggered_by_id'],
            ['principal.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_eval_run_eval_suite_id'), 'eval_run', ['eval_suite_id'], unique=False
    )
    op.create_table(
        'metric',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('capability_id', sa.Uuid(), nullable=True),
        sa.Column('agent_id', sa.Uuid(), nullable=True),
        sa.Column('skill_id', sa.Uuid(), nullable=True),
        sa.Column('tool_id', sa.Uuid(), nullable=True),
        sa.Column('metric_name', sa.String(length=255), nullable=False),
        sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column('unit', sa.String(length=64), nullable=True),
        sa.Column('is_realization_score', sa.Boolean(), nullable=False),
        sa.Column('weakest_contributor_agent_id', sa.Uuid(), nullable=True),
        sa.Column('weakest_contributor_skill_id', sa.Uuid(), nullable=True),
        sa.Column('weakest_contributor_tool_id', sa.Uuid(), nullable=True),
        sa.Column('otel_resource_ref', sa.String(length=255), nullable=True),
        sa.Column(
            'computed_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            '((capability_id IS NOT NULL AND agent_id IS NULL AND skill_id IS NULL AND tool_id IS NULL) OR (agent_id IS NOT NULL AND capability_id IS NULL AND skill_id IS NULL AND tool_id IS NULL) OR (skill_id IS NOT NULL AND capability_id IS NULL AND agent_id IS NULL AND tool_id IS NULL) OR (tool_id IS NOT NULL AND capability_id IS NULL AND agent_id IS NULL AND skill_id IS NULL))',
            name='ck_metric_one_scope',
        ),
        sa.CheckConstraint(
            '(weakest_contributor_agent_id IS NULL AND weakest_contributor_skill_id IS NULL AND weakest_contributor_tool_id IS NULL) OR ((weakest_contributor_agent_id IS NOT NULL AND weakest_contributor_skill_id IS NULL AND weakest_contributor_tool_id IS NULL) OR (weakest_contributor_skill_id IS NOT NULL AND weakest_contributor_agent_id IS NULL AND weakest_contributor_tool_id IS NULL) OR (weakest_contributor_tool_id IS NOT NULL AND weakest_contributor_agent_id IS NULL AND weakest_contributor_skill_id IS NULL))',
            name='ck_metric_weakest_contributor_at_most_one',
        ),
        sa.ForeignKeyConstraint(
            ['agent_id'],
            ['agent.id'],
        ),
        sa.ForeignKeyConstraint(
            ['capability_id'],
            ['capability.id'],
        ),
        sa.ForeignKeyConstraint(
            ['skill_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tool_id'],
            ['tool.id'],
        ),
        sa.ForeignKeyConstraint(
            ['weakest_contributor_agent_id'],
            ['agent.id'],
        ),
        sa.ForeignKeyConstraint(
            ['weakest_contributor_skill_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['weakest_contributor_tool_id'],
            ['tool.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_metric_tenant_id'), 'metric', ['tenant_id'], unique=False)
    op.create_table(
        'skill_graph_node',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('skill_id', sa.Uuid(), nullable=False),
        sa.Column('node_key', sa.String(length=255), nullable=False),
        sa.Column(
            'node_type',
            sa.Enum('agent', 'skill', 'tool', name='graph_node_type'),
            nullable=False,
        ),
        sa.Column('agent_id', sa.Uuid(), nullable=True),
        sa.Column('skill_ref_id', sa.Uuid(), nullable=True),
        sa.Column('tool_id', sa.Uuid(), nullable=True),
        sa.Column(
            'position',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            '((agent_id IS NOT NULL AND skill_ref_id IS NULL AND tool_id IS NULL) OR (skill_ref_id IS NOT NULL AND agent_id IS NULL AND tool_id IS NULL) OR (tool_id IS NOT NULL AND agent_id IS NULL AND skill_ref_id IS NULL))',
            name='ck_skill_graph_node_one_ref',
        ),
        sa.ForeignKeyConstraint(
            ['agent_id'],
            ['agent.id'],
        ),
        sa.ForeignKeyConstraint(
            ['skill_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['skill_ref_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tool_id'],
            ['tool.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('skill_id', 'node_key', name='uq_skill_graph_node_key'),
    )
    op.create_index(
        op.f('ix_skill_graph_node_skill_id'),
        'skill_graph_node',
        ['skill_id'],
        unique=False,
    )
    op.create_table(
        'tool_data_binding',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tool_id', sa.Uuid(), nullable=False),
        sa.Column('datasource_id', sa.Uuid(), nullable=True),
        sa.Column('dataproduct_id', sa.Uuid(), nullable=True),
        sa.Column(
            'access_mode',
            sa.Enum('read', 'write', 'read_write', name='data_binding_access_mode'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.CheckConstraint(
            '((datasource_id IS NOT NULL AND dataproduct_id IS NULL) OR (dataproduct_id IS NOT NULL AND datasource_id IS NULL))',
            name='ck_tool_data_binding_one_target',
        ),
        sa.ForeignKeyConstraint(
            ['dataproduct_id'],
            ['dataproduct.id'],
        ),
        sa.ForeignKeyConstraint(
            ['datasource_id'],
            ['datasource.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tool_id'],
            ['tool.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_tool_data_binding_tool_id'),
        'tool_data_binding',
        ['tool_id'],
        unique=False,
    )
    op.create_table(
        'skill_graph_edge',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('skill_id', sa.Uuid(), nullable=False),
        sa.Column('from_node_id', sa.Uuid(), nullable=False),
        sa.Column('to_node_id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['from_node_id'],
            ['skill_graph_node.id'],
        ),
        sa.ForeignKeyConstraint(
            ['skill_id'],
            ['skill.id'],
        ),
        sa.ForeignKeyConstraint(
            ['to_node_id'],
            ['skill_graph_node.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'skill_id', 'from_node_id', 'to_node_id', name='uq_skill_graph_edge'
        ),
    )
    op.create_index(
        op.f('ix_skill_graph_edge_skill_id'),
        'skill_graph_edge',
        ['skill_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_graph_edge_skill_id'), table_name='skill_graph_edge')
    op.drop_table('skill_graph_edge')
    op.drop_index(op.f('ix_tool_data_binding_tool_id'), table_name='tool_data_binding')
    op.drop_table('tool_data_binding')
    op.drop_index(op.f('ix_skill_graph_node_skill_id'), table_name='skill_graph_node')
    op.drop_table('skill_graph_node')
    op.drop_index(op.f('ix_metric_tenant_id'), table_name='metric')
    op.drop_table('metric')
    op.drop_index(op.f('ix_eval_run_eval_suite_id'), table_name='eval_run')
    op.drop_table('eval_run')
    op.drop_index(
        op.f('ix_dataproduct_lineage_dataproduct_id'), table_name='dataproduct_lineage'
    )
    op.drop_table('dataproduct_lineage')
    op.drop_index(
        op.f('ix_capability_realization_capability_id'),
        table_name='capability_realization',
    )
    op.drop_table('capability_realization')
    op.drop_index(op.f('ix_audit_event_tenant_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_tool_tenant_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_slug'), table_name='tool')
    op.drop_index(op.f('ix_tool_entity_id'), table_name='tool')
    op.drop_index(
        'ix_tool_current_version',
        table_name='tool',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('tool')
    op.drop_index(op.f('ix_skill_tenant_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_slug'), table_name='skill')
    op.drop_index(op.f('ix_skill_entity_id'), table_name='skill')
    op.drop_index(
        'ix_skill_current_version',
        table_name='skill',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('skill')
    op.drop_index(op.f('ix_role_binding_tenant_id'), table_name='role_binding')
    op.drop_index(op.f('ix_role_binding_principal_id'), table_name='role_binding')
    op.drop_table('role_binding')
    op.drop_index(op.f('ix_policy_tenant_id'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_eval_suite_tenant_id'), table_name='eval_suite')
    op.drop_table('eval_suite')
    op.drop_index(op.f('ix_datasource_tenant_id'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_slug'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_entity_id'), table_name='datasource')
    op.drop_index(
        'ix_datasource_current_version',
        table_name='datasource',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('datasource')
    op.drop_index(op.f('ix_dataproduct_tenant_id'), table_name='dataproduct')
    op.drop_index(op.f('ix_dataproduct_slug'), table_name='dataproduct')
    op.drop_index(op.f('ix_dataproduct_entity_id'), table_name='dataproduct')
    op.drop_index(
        'ix_dataproduct_current_version',
        table_name='dataproduct',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('dataproduct')
    op.drop_index(op.f('ix_capability_tenant_id'), table_name='capability')
    op.drop_index(op.f('ix_capability_slug'), table_name='capability')
    op.drop_index(op.f('ix_capability_entity_id'), table_name='capability')
    op.drop_index(
        'ix_capability_current_version',
        table_name='capability',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('capability')
    op.drop_index(op.f('ix_agent_tenant_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_slug'), table_name='agent')
    op.drop_index(op.f('ix_agent_entity_id'), table_name='agent')
    op.drop_index(
        'ix_agent_current_version',
        table_name='agent',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('agent')
    op.drop_index(op.f('ix_principal_tenant_id'), table_name='principal')
    op.drop_table('principal')
    op.drop_index(op.f('ix_environment_tenant_id'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
    # Hand-added: autogenerate does not emit DROP TYPE for the Postgres ENUMs
    # backing sa.Enum columns above. sa.Enum(...).drop() is a no-op on
    # dialects (e.g. SQLite) that don't model ENUM as a separate DDL object.
    bind = op.get_bind()
    for enum_name in (
        'lifecycle_state',
        'maturity_level',
        'classification',
        'layer',
        'memory_scope',
        'principal_kind',
        'environment_kind',
        'skill_kind',
        'graph_node_type',
        'data_binding_access_mode',
        'realizing_entity_type',
        'versioned_entity_kind',
        'eval_run_status',
        'policy_effect',
        'policy_scope_type',
        'audit_decision',
        'datasource_kind',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
