"""Add ModelEndpoint and Agent.model_binding_id

Revision ID: 0ba8c681a027
Revises: f911815a8772
Create Date: 2026-08-10 18:47:27.822617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0ba8c681a027'
down_revision: str | None = 'f911815a8772'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'model_endpoint',
        sa.Column(
            'protocol',
            sa.Enum('openai_compatible', 'anthropic_messages', name='model_protocol'),
            nullable=False,
        ),
        sa.Column('base_url', sa.String(length=2048), nullable=True),
        sa.Column('model', sa.String(length=255), nullable=False),
        sa.Column('auth_binding_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'lifecycle_state',
            # create_type=False: this ENUM type already exists -- every
            # other versioned entity table (0001_initial_schema.py) shares
            # it. Alembic's automatic per-table CREATE TYPE only memoizes
            # names it has already emitted *within this same upgrade run*
            # (see postgresql.ENUM._check_for_name_in_memos), so without
            # this it re-attempts CREATE TYPE here and fails with
            # `DuplicateObject` against a database that already ran 0001.
            postgresql.ENUM(
                'draft',
                'in_review',
                'approved',
                'published',
                'deprecated',
                'retired',
                name='lifecycle_state',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'maturity',
            postgresql.ENUM(
                'experimental',
                'beta',
                'stable',
                'deprecated',
                name='maturity_level',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'classification',
            postgresql.ENUM(
                'public',
                'internal',
                'confidential',
                'restricted',
                name='classification',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('created_by_id', sa.Uuid(), nullable=False),
        sa.Column('approved_by_id', sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(protocol != 'openai_compatible') OR (base_url IS NOT NULL)",
            name='ck_model_endpoint_openai_compatible_requires_base_url',
        ),
        sa.ForeignKeyConstraint(
            ['approved_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['principal.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['tenant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'entity_id', 'version', name='uq_model_endpoint_entity_version'
        ),
    )
    op.create_index(
        'ix_model_endpoint_current_version',
        'model_endpoint',
        ['entity_id'],
        unique=True,
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.create_index(
        op.f('ix_model_endpoint_entity_id'),
        'model_endpoint',
        ['entity_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_model_endpoint_slug'), 'model_endpoint', ['slug'], unique=False
    )
    op.create_index(
        op.f('ix_model_endpoint_tenant_id'),
        'model_endpoint',
        ['tenant_id'],
        unique=False,
    )
    # model_binding_id is a plain column, not a DB-level FK: it holds a
    # ModelEndpoint.entity_id (floating, resolved to whichever version is
    # currently `is_current` at the service layer), and entity_id alone
    # isn't a candidate key -- multiple version rows share it -- so it
    # can't back a foreign key.
    op.add_column('agent', sa.Column('model_binding_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'model_binding_id')
    op.drop_index(op.f('ix_model_endpoint_tenant_id'), table_name='model_endpoint')
    op.drop_index(op.f('ix_model_endpoint_slug'), table_name='model_endpoint')
    op.drop_index(op.f('ix_model_endpoint_entity_id'), table_name='model_endpoint')
    op.drop_index(
        'ix_model_endpoint_current_version',
        table_name='model_endpoint',
        postgresql_where=sa.text('is_current'),
        sqlite_where=sa.text('is_current'),
    )
    op.drop_table('model_endpoint')
    # ### end Alembic commands ###
    # Hand-added: autogenerate does not emit DROP TYPE for the Postgres ENUM
    # backing the `protocol` column above (see 0001_initial_schema.py for the
    # same note). sa.Enum(...).drop() is a no-op on dialects (e.g. SQLite)
    # that don't model ENUM as a separate DDL object.
    bind = op.get_bind()
    sa.Enum(name='model_protocol').drop(bind, checkfirst=True)
