apiVersion: v1
kind: Service
metadata:
  name: loom-catalog-api
  namespace: loom-catalog
  labels:
    app.kubernetes.io/name: loom-catalog-api
    app.kubernetes.io/part-of: loom-catalog
spec:
  selector:
    app.kubernetes.io/name: loom-catalog-api
  ports:
    - name: http
      port: 8000
      targetPort: http
